version: "3"

services:
  # Run 1 app for each subregion
  # North Shore, Hawaii
  app-north-shore:
    depends_on:
      - loki
      - prometheus
      - promtail
      - postgres
    build: ./app
    ports:
      - "3001:3001"
    volumes:
      - north-shore-logs:/var/log/
    environment:
      - CLOCK_SPEED=1000
      - SUB_REGION_ID=58581a836630e24c44878fcb
      - PGHOST=postgres
      - PGPASSWORD=surfana
    networks:
      - app-postgres
      - grafana-postgres
      - prometheus-loki-app
      - internet

  # North Orange County, California
  app-north-orange-county:
    depends_on:
      - loki
      - prometheus
      - promtail
    build: ./app
    ports:
      - "3002:3001"
    volumes:
      - north-shore-logs:/var/log/
    environment:
      - CLOCK_SPEED=1000
      - SUB_REGION_ID=58581a836630e24c44878fd6
      - PGHOST=postgres
      - PGPASSWORD=surfana
    networks:
      - app-postgres
      - grafana-postgres
      - prometheus-loki-app
      - internet

  # Run 1 sidecar promtail for each app
  # Each app shares a log directory volume with promtail
  promtail:
    depends_on:
        - loki
    image: grafana/promtail:v1.3.0
    volumes:
        - ./promtail/promtail.yml:/etc/promtail/promtail.yaml
        - north-orange-county-logs:/applogs
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
        - prometheus-loki-app

  promtail:
    depends_on:
        - loki
    image: grafana/promtail:v1.3.0
    volumes:
        - ./promtail/promtail.yml:/etc/promtail/promtail.yaml
        - north-shore-logs:/applogs
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
        - prometheus-loki-app

  # Run 1 postgres
  postgres:
    image: postgres:10.12
    restart: always
    volumes:
      - ./postgres/init-schema-db.sh:/docker-entrypoint-initdb.d/init-schema-db.sh
    environment:
      POSTGRES_PASSWORD: surfana
    networks:
        - app-postgres
        - grafana-postgres

  # Run 1 loki instance, configured in basic local mode
  loki:
    image: grafana/loki:v1.3.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-loki
      - prometheus-loki-app

  # Run 1 prometheus instance
  prometheus:
    image: prom/prometheus:v2.15.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/app.cfg
    networks:
      - world
      - prometheus-loki-app
      - grafana-prometheus
    command: >-
      --config.file=/app.cfg/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles

  # Run 1 Grafana, with provisioning
  grafana:
    depends_on:
      - loki
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: surfana
      GF_PATHS_PROVISIONING: "/app.cfg/provisioning"
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
    volumes:
      - ./grafana/config:/app.cfg
    networks:
      - world
      - grafana-loki
      - grafana-prometheus
      - grafana-postgres


networks:
  world:
  grafana-loki:
    internal: true
  grafana-prometheus:
    internal: true
  grafana-postgres:
    internal: true
  prometheus-loki-app:
    internal: true
  app-postgres:
    internal: true
  internet:
    driver: bridge

volumes:
  north-shore-logs:
  north-orange-county-logs: