server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  pipeline_stages:
  # This stage is only going to run if the scraped target has a label of
  # "name" with a value of "jaeger-agent".
  - match:
      selector: '{filename="/var/log/subregion.log"}'
      stages:
      # The JSON stage reads the log line as a JSON string and extracts
      # the expressions fields from the object for use in further stages.
      - json:
          expressions:
            level: level
            spotName: spotName
            spotId: spotId
            subregionName: subregionName
            subregionId: subregionId
            commentary: commentary
            commentaryType: commentaryType
            timeBlock: timeBlock

      # The labels stage pulls the value from each field that was extracted
      # from the previous stage and promotes it to a label.
      - labels:
          level:
          spotName:
          spotId:
          subregionName:
          subregionId:
          commentary:
          commentaryType:
          timeBlock:

