{
 "title": "Spot Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "spotName", "label": "Spot Name", "query": "label_values(spotName)" },
   {
    "name": "spotCameraStillUrl",
    "query": "select still_url from cameras where spot_name='[[spotName]]'"
   },
   {
    "name": "spotCameraRewindClip",
    "query": "select rewind_clip from cameras where spot_name='[[spotName]]'"
   },
   {
    "name": "spotCameraStreamUrl",
    "query": "select stream_url from cameras where spot_name='[[spotName]]'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"text-align:center\">Conditions</h2>\n\n\n\n"
  },
  {
   "title": "Overall Rating",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "conditions_rating{spotName=\"[[spotName]]\"}",
     "legendFormat": "{{timeBlock}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 2 },
   "content": "<h1>Latest Highlight</h1>\n<video height=\"400\" controls autoplay>\n  <source src=\"[[spotCameraRewindClip]]\" type=\"video/mp4\">\nYour browser does not support the video tag.\n</video>\n<br>\n<br>\n\n<h3>Wanna watch live? Start streaming <a href=\"[[spotCameraStreamUrl]]\" target=\"_blank\">here</a></h3>\n\n\n"
  },
  {
   "title": "Recent Reports",
   "type": "logs",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "{spotName=\"[[spotName]]\",commentaryType=\"human_relation\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 17 },
   "content": "\n<h1 style=\"text-align:center\">Swelll</h2>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "content": "\n<h1 style=\"text-align:center\">Tide</h2>\n\n\n\n"
  },
  {
   "title": "Direction",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(swell_direction_min_degrees{spotName=\"[[spotName]]\"} + swell_direction_max_degrees{spotName=\"[[spotName]]\"}) / 2",
     "legendFormat": "{{swellId}}"
    }
   ]
  },
  {
   "title": "Height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "lengthft" }
   ],
   "targets": [
    {
     "expr": "tide_height_feet{spotName=~\"[[spotName]]\"}",
     "legendFormat": "Tide Height"
    }
   ]
  },
  {
   "title": "Max Wave Heights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swell_height_feet{spotName=\"[[spotName]]\"} ",
     "legendFormat": "{{swellId}}"
    }
   ]
  },
  {
   "title": "Period",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "swell_period_feet{spotName=\"[[spotName]]\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 25 },
   "content": "\n<h1 style=\"text-align:center\">Wind</h2>\n\n\n\n"
  },
  {
   "title": "Speed & Gusts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "velocityknot" }
   ],
   "targets": [
    {
     "expr": "wind_speed_kts{spotName=~\"[[spotName]]\"}",
     "legendFormat": "Wind Speed"
    },
    {
     "expr": "wind_gust_kts{spotName=~\"[[spotName]]\"}",
     "legendFormat": "Wind Gusts"
    }
   ]
  },
  {
   "title": "Direction",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 },
   "targets": [
    {
     "expr": "wind_direction_degrees{spotName=~\"[[spotName]]\"}",
     "legendFormat": "Wind Speed"
    }
   ]
  }
 ]
}