{
 "title": "World Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "subregionName", "label": "Subregion", "query": "label_values(subregionName)\t" },
   { "name": "timeBlock", "query": "label_values(timeBlock)" }
  ]
 },
 "panels": [
  {
   "title": "Poor to Fair Spots",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"} <= bool 2)"
    }
   ]
  },
  {
   "title": "Fair to Good Spots",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"} >= bool 0) - sum(conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"} <= bool 2) - sum(conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"} >= bool 5) "
    }
   ]
  },
  {
   "title": "Good to Epic Spots",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"} >= bool 5)"
    }
   ]
  },
  {
   "title": "Spot Ratings",
   "type": "table",
   "gridPos": { "h": 25, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "conditions_surf_height_min_feet{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"}+0"
    },
    {
     "expr": "conditions_surf_height_max_feet{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"}+0"
    },
    {
     "expr": "tide_height_feet{subregionName=~\"[[subregionName]]\"}+0"
    },
    {
     "expr": "wind_speed_kts{subregionName=~\"[[subregionName]]\"}+0"
    },
    {
     "expr": "conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"}+0"
    }
   ]
  },
  {
   "title": "Spot Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 25, "w": 11, "x": 13, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "expr": "conditions_rating{timeBlock=\"[[timeBlock]]\",subregionName=~\"[[subregionName]]\"}"
    }
   ]
  }
 ]
}