apiVersion: 1

datasources:
- name: loki
  access: proxy
  type: loki
  url: http://loki:3100
  isDefault: false
  database: ''
  user: ''
  password: ''
  basicAuth: false
  id: 1
  orgId: 1
  readOnly: false
  jsonData:
    keepCookies: []
  typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
- name: prometheus
  access: proxy
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  orgId: 1
  editable: false
  jsonData:
    timeInterval: 10s
- name: postgres
  type: postgres
  url: postgres:5432
  database: postgres
  user: postgres
  secureJsonData:
    password: "surfana"
  jsonData:
    sslmode: "disable" # disable/require/verify-ca/verify-full
    maxOpenConns: 0         # Grafana v5.4+
    maxIdleConns: 2         # Grafana v5.4+
    connMaxLifetime: 14400  # Grafana v5.4+
    postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
    timescaledb: false